<input type="hidden" class="map-trigger" id="id0"/>
<input type="hidden" class="map-trigger" id="id1"/> 
<input type="hidden" class="map-trigger" id="id2"/> 
<input type="hidden" class="map-trigger" id="id2"/> 
<input type="hidden" class="map-trigger" id="id3"/>
<input type="hidden" class="map-trigger" id="id4"/>
<input type="hidden" class="map-trigger" id="id5"/>
<input type="hidden" class="map-trigger" id="id6"/> 
<input type="hidden" class="map-trigger" id="id7"/> 
<input type="hidden" class="map-trigger" id="id8"/> 
<input type="hidden" class="map-trigger" id="id9"/> 
<input type="hidden" class="map-trigger" id="id10"/> 
<input type="hidden" class="map-trigger" id="id11"/> 
<input type="hidden" class="map-trigger" id="id12"/> 
<input type="hidden" class="map-trigger" id="id13"/>
<input type="hidden" class="map-trigger" id="id14"/>
<input type="hidden" class="map-trigger" id="id15"/>
<input type="hidden" class="map-trigger" id="id16"/> 
<input type="hidden" class="map-trigger" id="id17"/> 
<input type="hidden" class="map-trigger" id="id18"/> 
<input type="hidden" class="map-trigger" id="id19"/> 